# This is a basic workflow to help you get started with Actions

name: Package

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v1

      - name: Create Package
        uses: BigWigsMods/packager@v2
        with:
          args: -d
